const KOREAN_MATCHED_TERM_GLOSSES: Readonly<Record<string, string>> = Object.freeze({
  '전환가액 조정': 'conversion price adjustment',
  전환가액: 'conversion price',
  리픽싱: 'conversion-price reset (refixing)',
  '신주 발행': 'issuance of new shares',
  신주모집: 'primary share offering',
  발행주식총수: 'total issued shares',
  '전환가능 주식수': 'shares issuable upon conversion',
  주식매수선택권: 'stock options',
  상환전환우선주: 'redeemable convertible preferred shares',
  오버행: 'share overhang',
  희석: 'dilution',
  '차입금 상환': 'debt repayment',
  '만기 도래': 'upcoming maturity',
  대환: 'replacement/refinancing loan',
  차환: 'debt refinancing/rollover',
  '상환 재원': 'repayment funding source',
  '원리금 상환': 'repayment of principal and interest',
  조기상환청구권: 'investor’s early-redemption put right',
  풋옵션: 'put option',
  '만기 연장': 'maturity extension',
  브릿지론: 'bridge loan',
  현금성자산: 'cash equivalents',
  '현금 소진': 'cash burn',
  '운전자금 부족': 'working-capital shortfall',
  운전자금: 'working capital',
  유동성: 'liquidity',
  계속기업: 'going concern',
  '영업현금흐름 적자': 'negative operating cash flow',
  '최소 매출액 약정': 'minimum-revenue covenant',
  '현금 회수기간': 'cash collection period',
  특수관계인: 'related party',
  이해상충: 'conflict of interest',
  최대주주: 'largest shareholder',
  관계사: 'affiliate',
  내부통제: 'internal controls',
  '이사회 독립성': 'board independence',
  '공정성 의견': 'fairness opinion',
  콜옵션: 'call option',
  의결권: 'voting rights',
  인허가: 'permits and approvals',
  '고객사 승인': 'customer approval',
  양산: 'volume production',
  '상업 생산': 'commercial production',
  '생산설비 증설': 'production-capacity expansion',
  임상시험: 'clinical trial',
  품목허가: 'regulatory product approval',
  '환경 인허가': 'environmental permits and approvals',
  시험가동: 'commissioning / trial operation',
  수율: 'production yield',
  '발사 일정': 'launch schedule',
  '시스템 통합': 'system integration',
  '가격 경쟁': 'price competition',
  '수요 둔화': 'demand slowdown',
  '고객 수요': 'customer demand',
  '원재료 가격': 'raw-material prices',
  전력요금: 'electricity tariffs',
  환율: 'exchange rate',
  '금리 상승': 'rising interest rates',
  '주가 변동성': 'share-price volatility',
  '시장 변동성': 'market volatility',
  경쟁사: 'competitor',
  '공모가 하회': 'trading below the IPO offer price',
  '변동 없음': 'no change',
  '참고 목적': 'for reference',
  납입일: 'payment date',
  청약일: 'subscription date',
  '상장 예정일': 'expected listing date',
  '일반 예금': 'ordinary bank deposit',
})

export function matchedTermEnglishGloss(term: string): string | null {
  return KOREAN_MATCHED_TERM_GLOSSES[term] ?? null
}
